### ISSUE TITLE
How to modify the code when input x have 3 dimensions?

### ISSUE THREAD

**Issue by YoshiPark** [Janus-Shiau/awd-lstm-tensorflow#1]
When I modified x to 3 dimension:[batch_size, time_step, hidden_size]， the program seems to not work:
Traceback (most recent call last):
  File "example_awd_lstm.py", line 158, in <module>
    test_with_sess_run(x)
  File "example_awd_lstm.py", line 60, in test_with_sess_run
    x_out, _ = lstm_cell(x, init_states)
  File "/home/punjiujam/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 371, in __call__
    *args, **kwargs)
  File "/home/punjiujam/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/punjiujam/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/home/punjiujam/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1591, in _maybe_build
    self.input_spec, inputs, self.name)
  File "/home/punjiujam/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/input_spec.py", line 123, in assert_input_compatibility
    str(x.shape.as_list()))
ValueError: Input 0 of layer weight_drop_lstm_cell_1 is incompatible with the layer: expected ndim=2, found ndim=3. Full shape received: [2, 10, 10]

**Comment by Janus-Shiau** [comment]
Hi YoshiPark,

Thank you for your question!

To be brief, check out `dynamic_rnn`.
In Tensorflow, all kinds of cells inheriting `RNNCell` take inputs with exactly 2 dimension. To handle the `time_step`, please turn to `tf.while_loop` or simple use `tf.nn.dynamic_rnn` or `tf.nn.static_rnn`.

For example:
```
rnn_cell = WeightDropLSTMCell(hidden_size, 
        weight_drop_kr=WEIGHT_DP_KR, use_vd=False)
initial_state = rnn_cell.zero_state(batch_size, dtype=tf.float32)

# x with shape [batch_size, time_step, hidden_size]
outputs, state = tf.nn.dynamic_rnn(rnn_cell, x,
        initial_state=initial_state,
        dtype=tf.float32)
```

Reference: 
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/nn/dynamic_rnn
